language: node_js
services:
  - docker

before_script:
  - docker build -t shschiff/employees-test -f Dockerfile.test .
script:
  - docker run --rm -p 3000:3000 shschiff/employees-test
after_success:
  - docker build -t shschiff/employees -f Dockerfile.prod .
  - docker push shimschiff/employees
deploy:
  provider: script
  script: echo "ansible.sh"
  on:
    branch: master
after_failure:
  - echo "tests failed - rejected"
