language: node_js
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fd565dd073a0_key -iv $encrypted_fd565dd073a0_iv
  -in deploy/deploy_key.enc -out deploy/deploy_key -d
install: true
before_script:
- docker build -t shschiff/employees-test -f deploy/Dockerfile.test .
script:
- docker run --rm -p 3000:3000 shschiff/employees-test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- export REPO=shschiff/employees
- docker build -f deploy/Dockerfile.prod -t ${REPO} .
- docker push ${REPO}

- sudo apt-get install -y software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get -y update
- sudo apt-get install -y ansible

- eval "$(ssh-agent -s)"
- chmod 600 deploy/deploy_key
- ssh-add deploy/deploy_key
- ansible all -m ping -i deploy/ansible.hosts -u ec2-user
- ansible-playbook deploy/main.yml -i deploy/ansible.hosts
after_failure:
- echo "tests failed - rejected"
